version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: silo-hc-monitor-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: silo-hc-monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - silo-hc-monitor-network

volumes:
  postgres-data:

networks:
  silo-hc-monitor-network:
    driver: bridge
